apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: kubetest
  labels:
    app: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
      - name: authelia
        image: authelia/authelia:4.9 #  <----- You should use an explicit version here docker pull 
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
        volumeMounts:
        - name: config-volume
          mountPath: /etc/authelia
        - name: users-volume
          mountPath: /config       
        - name: dbvolume
          mountPath: /var/lib/authelia       
      volumes:
      - name: dbvolume
        emptyDir:
          {}
      - name: config-volume
        configMap:
          name: authelia-config
          items:
          - key: configuration.yml
            path: configuration.yml
      - name: users-volume
        configMap:
          name: authelia-users
          items:
          - key: users_database.yml 
            path: users_database.yml           
