apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kubetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.5
          # command: ["/bin/sh"]
          # args: ["-c", "psql -h localhost -U root -p 5432 postgresdb", "create database testdb"]
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: pgdata
              name: postgredb
          env:
            # need to define PGDATA env var because not using the default /var/lib/postgresql/data, but a subpath under it.
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgresql-pvc
