apiVersion: v1
kind: Service
metadata:
  name: urlcontainer
  namespace: kubetest
  labels:
    run: urlcontainer
spec:
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: urlcontainer
